# Generated by Django 5.2.6 on 2026-02-21 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='flat_occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('photo', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='feedback_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('feedback', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='emergency_notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('FLAT_OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='book_common_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('FLAT_OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='flat_owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('proof', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
                ('Status', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facilities_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=100)),
                ('FLAT_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_owner')),
            ],
        ),
        migrations.CreateModel(
            name='flat_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField()),
                ('squarefeet', models.BigIntegerField()),
                ('rooms', models.BigIntegerField()),
                ('flatnumber', models.BigIntegerField()),
                ('floor', models.BigIntegerField()),
                ('place', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('FLAT_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_owner')),
            ],
        ),
        migrations.AddField(
            model_name='flat_occupant',
            name='FLAT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_table'),
        ),
        migrations.CreateModel(
            name='notification_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('FLAT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_table')),
            ],
        ),
        migrations.CreateModel(
            name='rent_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent', models.BigIntegerField()),
                ('pending_rent', models.BigIntegerField()),
                ('date', models.DateField()),
                ('duration', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('FLAT_OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='payment_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('RENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rent_table')),
            ],
        ),
        migrations.CreateModel(
            name='security_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('image', models.FileField(upload_to='')),
                ('proof', models.FileField(upload_to='')),
                ('FLAT_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_owner')),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='duty_to_security_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('SECURITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.security_table')),
            ],
        ),
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('proof', models.FileField(upload_to='')),
                ('image', models.FileField(upload_to='')),
                ('place', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='service_request_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_field', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('FLAT_OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='assign_service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('SERVICE_PROVIDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service_provider')),
                ('SERVICE_REQUEST', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service_request_table')),
            ],
        ),
        migrations.CreateModel(
            name='Service_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('SERVICE_PROVIDER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service_provider')),
            ],
        ),
        migrations.AddField(
            model_name='service_request_table',
            name='SERVICE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.service_table'),
        ),
        migrations.CreateModel(
            name='surveillance_camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_no', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('FLAT_OWNER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_owner')),
            ],
        ),
        migrations.CreateModel(
            name='suspicious_activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('date', models.DateField()),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.surveillance_camera')),
            ],
        ),
        migrations.CreateModel(
            name='visitor_entry_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Relation', models.CharField(max_length=50)),
                ('No_of_persons', models.IntegerField()),
                ('date', models.DateField()),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('Status', models.CharField(default='pending', max_length=50)),
                ('OCCUPANT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.flat_occupant')),
            ],
        ),
        migrations.CreateModel(
            name='QR_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qrcode', models.ImageField(upload_to='qrcode/')),
                ('date', models.DateField()),
                ('VISITOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.visitor_entry_table')),
            ],
        ),
    ]
