# Generated by Django 5.2.6 on 2026-02-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveillance_camera',
            name='status',
            field=models.CharField(default='notification', max_length=100),
        ),
    ]
