# Generated by Django 5.2.6 on 2026-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_surveillance_camera_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspicious_activities',
            name='status',
            field=models.CharField(default='notification', max_length=100),
        ),
    ]
